anaTupleDef: AnaProd/HH_bbWW/anaTupleDef.py
analysis_import: Analysis.hh_bbww
signal_types:
  - GluGluToRadion
  - GluGlutoRadion
  - GluGluToBulkGraviton
corrections:
  - mu
  - trg
  - ele
  - eleES
  - pu
  - JEC
  - JER
  - btagShape

tagger_name: "particleNet"
bjet_preselection_branch : "Jet_sel"
#This is for Analysis Selection
channelSelection:
  - e
  - mu
  - eE
  - eMu
  - muMu

#This is for Histogram Making
channels_to_consider:
  - e
  - mu
  - eE
  - eMu
  - muMu

channelDefinition:
  e: 10 #Second lepton doesn't exist
  mu: 20
  eE: 11
  eMu: 12
  muMu: 22

categories:
  - inclusive
  - boosted
  - baseline
  - res1b
  - res2b

region_default: SR

QCDRegions:
  - OS_Iso
  - SS_Iso
  - OS_AntiIso
  - SS_AntiIso
  - Zpeak_0b
  - Zpeak_1b
  - Zpeak_2b
  - ZVeto_0b
  - ZVeto_1b
  - ZVeto_2b
  - TTbar_CR

boosted_categories: []


triggers:
  e: [singleEleWpTight]
  mu: [singleIsoMu]
  eE: [singleEleWpTight]
  eMu: [singleIsoMu]
  muMu: [singleIsoMu]

application_regions:
  HLT_singleEleWpTight:
    region_name: SingleE_region
    region_cut: (true)
  HLT_singleIsoMu:
    region_name: SingleMu_region
    region_cut: (true)

sample_types_to_merge: #Use this for what samples to run limits on
  - DY
  - TT
  - W
  - ST
  - TTX
  - VV
  - TTV
  - TTVV
  - QCDMu
  - QCDEM
  - QCD_PT
  - QCD_HT

samples_to_skip_hist:
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-1000
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-1200
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-1400
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-1600
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-1800
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-2000
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-2500
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-250
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-260
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-270
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-280
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-3000
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-300
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-350
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-4000
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-450
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-5000
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-550
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-600
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-650
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-700
  - GluGlutoRadiontoHHto2B2Vto2B2L2Nu_M-800

var_only_boosted: []

unc_to_not_consider_boosted: []

uncs_to_exclude:
  Run3_2022: []
  Run3_2022EE: []

storeExtraJets: False
scales:
  - Up
  - Down
deepTauVersion: 2p1
met_type: "PuppiMET"
vars_to_plot:
  - lep1_pt
  - lep2_pt
  - lep1_eta
  - lep2_eta
  - lep1_phi
  - lep2_phi
  # - lep1_charge
  # - lep2_charge
  - lep1_Muon_pfRelIso04_all
  - lep2_Muon_pfRelIso04_all
  - lep1_Electron_miniPFRelIso_all
  - lep2_Electron_miniPFRelIso_all
  - bjet1_btagPNetB
  - bjet2_btagPNetB
  - diLep_mass
  - Lep1Jet1Jet2_mass
  - Lep1Lep2Jet1Jet2_mass
  - Njets
  - bjet1_pt
  - bjet2_pt
  - HT
  - dR_dilep
  - dR_dibjet
  - dR_dilep_dibjet
  - dPhi_lep1_lep2
  - dPhi_jet1_jet2
  - dPhi_MET_dilep
  - dPhi_MET_dibjet
  - min_dR_lep0_jets
  - min_dR_lep1_jets
  - bb_mass
  - bb_mass_PNetRegPtRawCorr
  - bb_mass_PNetRegPtRawCorr_PNetRegPtRawCorrNeutrino
  - PuppiMET_pt
  - PuppiMET_phi
